### PR TITLE
Fix the camelCasing of meta keys as per camelizeKeys option

### PR DESCRIPTION
**Pull request by InputOutput**
Should resolve https://github.com/yury-dymov/json-api-normalizer/issues/27

### CODE REVIEW

**Comment by yury-dymov** [comment]
Thank you! Just published new version with this change

**Comment by InputOutput** [comment]
👍

**Comment by Startouf** [comment]
Ah well, we just realized our previous devs had been coding around this bug, and since the update we have many broken flows because of the new camelCasing. I guess this was unavoidable and highlights our missing tests.

**Comment by yury-dymov** [comment]
@Startouf I am terribly sorry :/

**Pull request merged**
